### ISSUE TITLE
SDL.SDL_MapRGB(), unable to get surface->format

### ISSUE THREAD

**Issue by TommyAGK** [flibitijibibo/SDL2-CS#101]
Hi, 

I am trying to use the mapRGB function and it asks for an int pointer to a pixelformat, according to the source code the surface object should contain a property that holds the format required.

But the command used to retrieve the surface does not yield the correct type of surface?

How do I get a valid surface with the appropriate sub-elements that is ment to be available?

screenSurfacePtr = SDL.SDL_GetWindowSurface(windowPtr);
SDL.SDL_FillRect(screenSurfacePtr, IntPtr.Zero, 0x1284718); // works
SDL.SDL_FillRect(screenSurfacePtr, IntPtr.Zero, SDL.SDL_MapRGB(screenSurfacePtr.format, 0xff,0xff,0xff); // error, object does not exsist. also the

SDL.SDL_Pixelformat returns a uint. not a pointer, so i cant reference that.

**Comment by flibitijibibo** [comment]
You have to cast to SDL_Surface* to get the format. Whatever function is doing this will need to be marked as unsafe.
