### ISSUE TITLE
(minor) (nuget) Install failure

### ISSUE THREAD

**Issue by graspee** [flibitijibibo/SDL2-CS#102]
Installing SDL2-CS in visual studio with the nuget package manager fails because it tries to install sdl2.0.3 as a dependency and sdl2.0.3 nuget package fails if you try to install it into a c# project rather than a c++ one. 

The solution is just to uncheck the box to stop it trying to install deps and then just manually dropping an sdl DLL into the output folder but I thought you might want to make it neater.

**Comment by flibitijibibo** [comment]
All NuGet packages of any of my software is both unofficial and also unauthorized. While authorization is not required given my license, it's telling that this person couldn't even put in the effort of telling me who they are so I could tell you that it's their fault and not mine.

**Comment by graspee** [comment]
Sorry, I just assumed that it was you that had put it up there. Apologies.
