### ISSUE TITLE
SDL_MapRGB

### ISSUE THREAD

**Issue by horseyhorsey** [flibitijibibo/SDL2-CS#103]
Hi...just something here that's confused me a bit. You can see here the stick man using a color key to remove the Cyan background.

It's like the RGB is BGR ? If I set it 0, 255, 255 it removes the sun (yellow). For working to remove the cyan it's 255, 255, 0

Thanks. I am also wondering whilst I am here that I have to create the texture surface twice just to get the format then set a color key....You can see this from the image....is there a better way using this wrapper? 

![rgb](https://cloud.githubusercontent.com/assets/5377332/14227486/e14e1836-f8f6-11e5-9f24-c750fd267b08.png)

**Comment by flibitijibibo** [comment]
Have you checked the format of the surface? I don't see code checking for the pixel format...

You may be interested in the SDL_PixelFormat and SDL_Palette structures as well as their related functions:

https://wiki.libsdl.org/SDL_PixelFormat
https://wiki.libsdl.org/SDL_Palette

**Comment by horseyhorsey** [comment]
Oh I see, it was in BGRA8888! I'm new to this so thanks for taking time to point that one out. I am just wondering now would it be wise just to convert all incoming surfaces to something like RGBA8888?

**Comment by flibitijibibo** [comment]
I would keep the formats as-is, SDL2 is usually picking the optimal format for the platform and so should be left alone.

**Comment by horseyhorsey** [comment]
OK gotcha, thanks, it's been an eye opener! Thanks for supplying this wrapper and I'll have to check some of those game ports you've done....all the best!
