### ISSUE TITLE
SDL_BITSPERPIXEL is defined incorrectly: it should mask 8 bits, not 4

### ISSUE THREAD

**Issue by holmak** [flibitijibibo/SDL2-CS#105]
In the SDL2 source code, SDL_BITSPERPIXEL is defined as:

`// SDL_pixels.h`
`#define SDL_BITSPERPIXEL(X) (((X) >> 8) & 0xFF)`

In SDL2-CS, it is defined as:

`// SDL2.cs`
`public static byte SDL_BITSPERPIXEL(uint X)`
`{`
`	return (byte) ((X >> 8) & 0x0F);`
`}`

The bitmasks don't match; "bits per pixel" is an 8-bit value. The mask in SDL2-CS needs to be changed from 0x0F to 0xFF.

**Comment by flibitijibibo** [comment]
You wouldn't believe this, but I just ran into this the other day on Atom Zombie Smasher... guess I should have pushed this _before_ sending out builds and not after :P

This should do it:

https://github.com/flibitijibibo/SDL2-CS/commit/6f158b9f7997440c49dcde674e7e19ed2decd185

**Comment by holmak** [comment]
Thanks for the quick response!
