### ISSUE TITLE
How to use SDL_EventFilter?

### ISSUE THREAD

**Issue by KingSora** [flibitijibibo/SDL2-CS#110]
Hello!

How is SDL_EventFilter working in C#? I've this so far:
```
SDL.SDL_SetEventFilter(new SDL.SDL_EventFilter(new Func<IntPtr, IntPtr, int>((IntPtr d1, IntPtr d2) => {
   return 1;
})), IntPtr.Zero);
```

The question is, how do I indentify the event which I am filtering? I've just a IntPtr there and no possibility to get a SDL_Event out of it.

Best regards,
Sora

**Comment by tstavrianos** [comment]
As a start, SDL_EventFilter is declared as a delegate, so I guess you need change your code to `SDL.SDL_SetEventFilter((d1, d2) => {return 1;}, IntPtr.Zero);`.

As for the actual filtering, you will need to Marshal d2 to an SDL_Event and then do your filtering on the new object.

For instance, for unsafe: `SDL.SDL_Event ev = *(SDL.SDL_Event*)d2;` 
and the same with marshal: `SDL.SDL_Event ev = System.Runtime.InteropServices.Marshal.PtrToStructure<SDL.SDL_Event>(d2);`

**Comment by KingSora** [comment]
Thank you, it works! :)

**Comment by flibitijibibo** [comment]
Glad it was a quick fix!
