### ISSUE TITLE
Sound doesn't work

### ISSUE THREAD

**Issue by Jegqamas** [flibitijibibo/SDL2-CS#112]
Hello, I've using SDL2 # for a while to convert my c++ project into c#, it works for me fine until i tried to write sound playback for my project. The probelm is that the same code is working when compiling with c++, but never work in c#.
Code is C#:
`using System;
using System.Runtime.InteropServices;
using SDL2;
using MyNes.Core;

namespace MyNesSDL
{
    public class AudioProvider : IAudioProvider
    {
        byte[] audio_samples;
        int samples_count;
        ushort buffer_size;
        int w_pos;
        int r_pos;
        bool ready;
        bool enabled;

        SDL.SDL_AudioSpec specs;

        public bool IsPlaying { get; private set; }
        public bool IsRecording { get; private set; }

        public void Initialize(bool pl_enabled, int frequency, ushort buffer_size_bytes)
        {
            ready = false;
            enabled = pl_enabled;
            buffer_size = buffer_size_bytes;
            Console.WriteLine("SDL: Initializing audio ...");

            SDL.SDL_Init(SDL.SDL_INIT_AUDIO);

            specs = new SDL.SDL_AudioSpec();
            SDL.SDL_AudioSpec specs1 = new SDL.SDL_AudioSpec();// dummy

            specs.channels = 1;
            specs.format = SDL.AUDIO_S16SYS;
            specs.freq = frequency;
            specs.samples = buffer_size_bytes;
            specs.callback = my_audio_callback;

            if (SDL.SDL_OpenAudio(ref specs, ref specs1) < 0)
            {
                Console.WriteLine("!!!! SDL: Failed to open audio: %s", SDL.SDL_GetError());
            }

            samples_count = buffer_size * 20;
            audio_samples = new byte[samples_count];

            w_pos = 0;
            r_pos = w_pos + buffer_size;

            IsPlaying = false;

            SDL.SDL_PauseAudio(enabled ? 0 : 1);

            ready = true;

            Console.WriteLine("SDL: Audio initialized success.");
        }
        public void Pause()
        {
            if (IsPlaying)
            {
                IsPlaying = false;
                SDL.SDL_PauseAudio(1);
            }
        }
        public void Play()
        {
            if (!IsPlaying)
            {
                IsPlaying = true;
                SDL.SDL_PauseAudio(0);
            }
        }
        public void Shutdown()
        {
        }
        public void Update(ref short[] samples)
        {
// this should be called by another thread to fill the internal buffer.
// If not called at all, playback should still play since the audio_samples is already fill with 0
            if (!enabled)
                return;
            if (!ready)
                return;
            for (int i = 0; i < samples.Length; i++)
            {
                audio_samples[w_pos] = (byte)(samples[i] & 0xFF);
                w_pos++;
                if (w_pos >= samples_count)
                    w_pos -= samples_count;

                audio_samples[w_pos] = (byte)(samples[i] >> 8);
                w_pos++;
                if (w_pos >= samples_count)
                    w_pos -= samples_count;
            }
        }
        private void my_audio_callback(IntPtr userdata, IntPtr stream, int len)
        {
// After debugging, this method is called once then the program crashes.
            if (!enabled)
                return;
            if (!ready)
                return;
            byte[] buffer = new byte[len];
        
            for (int i = 0; i < len; i++)
            {
               buffer[i] = audio_samples[r_pos];

                r_pos++;
                if (r_pos >= samples_count)
                    r_pos -= samples_count;
            }

            Marshal.Copy(buffer, 0, stream, len);
        }
    }
}
`

Working code on C++ (using same library of latest version of SDL2)
#include <string>
#include <iostream>
#include "VideoOut.h"
#include <SDL2/SDL.h>

namespace AudioOut
{
bool IsPlaying;
Uint8* audio_samples;
long samples_count;
int buffer_size;
int w_pos;
int r_pos;
short temp_value;
bool ready;
bool enabled;
SDL_AudioSpec* wav_spec_desigred;

void my_audio_callback(void *userdata, Uint8 * stream, int len);

void Initialize(const bool pl_enabled, const uint32_t frequency,const int buffer_size_bytes)
{
    ready = false;
    enabled= pl_enabled;
    buffer_size=buffer_size_bytes;
    std::cout << "SDL: Initializing audio ...\n";
    SDL_Init(SDL_INIT_AUDIO);
    wav_spec_desigred = new SDL_AudioSpec();
    wav_spec_desigred->channels = 1;
    wav_spec_desigred->format = AUDIO_S16SYS;
    wav_spec_desigred->freq = frequency;
    wav_spec_desigred->samples = buffer_size;
    wav_spec_desigred->callback = my_audio_callback;
    wav_spec_desigred->userdata = NULL;

    SDL_OpenAudio(wav_spec_desigred, NULL);

    samples_count = buffer_size * 20;
    audio_samples = new Uint8[samples_count];

    for (int i = 0; i < samples_count; i++)
        audio_samples[i] = rand() % 100;
    w_pos = 0;
    r_pos = w_pos + buffer_size;

    IsPlaying = false;

    SDL_PauseAudio(enabled ?1:0);

    ready = true;

    std::cout <<"SDL: Audio initialized success.\n";
}
void Play()
{
    if (!IsPlaying)
    {
        IsPlaying = true;
        SDL_PauseAudio(0);
    }
}
void Pause()
{
    if (IsPlaying)
    {
        IsPlaying = false;
        SDL_PauseAudio(1);
    }
}
void PutSample(const short& sample)
{
    if (!enabled)
        return;
    if (!ready)
        return;

    audio_samples[w_pos] = sample & 0xFF;
    w_pos++;
    if (w_pos >= samples_count)
        w_pos -= samples_count;

    audio_samples[w_pos] = sample >> 8;
    w_pos++;
    if (w_pos >= samples_count)
        w_pos -= samples_count;
}
void my_audio_callback(void *userdata, Uint8 *stream, int len)
{
    if (!enabled)
        return;
    if (!ready)
        return;

    for (int i = 0; i < len; i++)
    {
        stream[i] = audio_samples[r_pos];

        r_pos++;
        if (r_pos >= samples_count)
            r_pos -= samples_count;
    }
}
void Shutdown()
{
    delete [] audio_samples;
    delete [] wav_spec_desigred;
}
}
`
Is there is something wrong with my code.
Thanks and sorry for my English

**Comment by flibitijibibo** [comment]
Not sure what the formatting thing is on GitHub... are you using "```" for code blocks?

A couple things that could be wrong:
- .NET is collecting the callback function pointer when it shouldn't. I think the debugger warns on this happening, but maybe not if it's part of a struct (though I would expect it not to collect at that point?).
- The extra stuff in the audio callback could be an issue. Instead of allocating a byte[], use
```
private void my_audio_callback(IntPtr userdata, IntPtr stream, int len)
{
    unsafe
    {
        byte* streamPtr = (byte*) stream;
        for (int i = 0; i < len; i++)
        {
            streamPtr[i] = audio_samples[r_pos];

            r_pos++;
            if (r_pos >= samples_count)
                r_pos -= samples_count;
        }
    }
}
```

It's hard to debug locally because I don't have a sample program, just the sample class.

**Comment by Jegqamas** [comment]
Hello,
Thanks for the quick response. Actually, I tried the code and still doesn't work :(
Here is the complete source:
https://www.dropbox.com/s/u7472rzb602bhzm/mynessdlsource.zip?dl=0

The code of SDL is in MyNesSDL project, the release goes to MyNesSDL/bin/Release
The code of the Audio can be found at MyNesSDL/Providers/AudioProvider.cs
It compiles ok, I included all required SDL2 libraries in the Release folder, when a game is presented as game.nes file in the release folder, the emu should be able to run that game.
You can pass the rom file you want to run as a parameter to MyNesSDL and it should work.
In AudioProvider.cs, when disabling the line specs.callback = my_sound_callback; line, the emu run without problems, and the game can be played. In other case, the emu crashes after one callback.

Thanks for help, this is really a good work, my project was work with SDL.NET <http://sourceforge.net/projects/mynes/>, but it was very buggy and slow. With this one, it run very fast wihtout problems (except for the sound) :D

**Comment by flibitijibibo** [comment]
If it's the callback causing the issue then it's almost certainly the GC - definitely if the function signature matches (which it should).

That said, there's still a lot of copying going around in the application. Would it be any easier to just use SDL_QueueAudio instead?

https://wiki.libsdl.org/SDL_QueueAudio

You can pin the Update() array and pass it that way instead of storing a staging buffer and copying to that and then copying to the stream pointer. Admittedly SDL will be doing that with the queue, but at least that will all be 100% native rather than it constantly hopping back and forth between managed and unmanaged.

**Comment by flibitijibibo** [comment]
Took a quick look at the source, one more thing to remember is to have `[STAThread]` on your Main function. I dunno if that'll matter here, but it will for things like input later on.

**Comment by Jegqamas** [comment]
I tried the STAThread but still no luck, I'm going to replace the callback with SDL_QueueAudio .
Thanks again 👍

**Comment by Jegqamas** [comment]
Hello,
I add SDL_QueueAudio, since the SDL_QueueAudio is not implemented with SDL2# (i have the latest version), i had to include it in the SDL2# source myself.
Also, I could not found a proper example how to use the SDL_QueueAudio, so i tried on my own. 
The emu run this time, but no sound play at all. I added some code to see if the Queue is working or not, I added a code for SDL_GetQueuedAudioSize, used it to output the queue to see if the SDL_QueueAudio works or not. 
Turns out it works, but no queued audio played, it only fill the queue with data but the data is never used. Please help !
Here is the complete source: https://www.dropbox.com/s/isvtmwlk4jgxnf9/mynessdlsource.zip?dl=0
Thanks again :)

**Comment by flibitijibibo** [comment]
That's something I wanted to bring up... what exactly is your versioning scheme? The version you have, to the best of my knowledge, is from 2014. Are you downloading it from somewhere specific...?

**Comment by Jegqamas** [comment]
I downloaded the SDL2# from here, this page on github. For the SDL_QueueAudio and SDL_GetQueuedAudioSize, i added them myself.
I downloaded the SDL2# verson from here: https://github.com/flibitijibibo/SDL2-CS/releases (B1 2a2bdc2)

**Comment by flibitijibibo** [comment]
Try this one:

https://github.com/flibitijibibo/SDL2-CS/archive/master.zip

**Comment by Jegqamas** [comment]
Okay, I'll try it ASAP. Thanks :)

**Comment by Jegqamas** [comment]
I implemented the code, i had to made some changes, it is indeed better and smaller. The emu work, but still sound not playable. I've never tried the callback method yet with this new code, I will do this now.
Here is the new source: https://www.dropbox.com/s/isvtmwlk4jgxnf9/mynessdlsource.zip?dl=0

**Comment by flibitijibibo** [comment]
You're probably better off ignoring the emulator for now and just making an example Program.cs file that just constantly emits a sine wave, to verify that the C# portion works. For all we know the Update() data is blank, or the GCHandle needs to be stored, or various other things that are hard to trace without being able to step through everything (which managed code does not really provide).

The good news is that an example's probably about 15 lines plus the sine generator, so it shouldn't be too hard to make something...

**Comment by Jegqamas** [comment]
Okay,
I implemented the callback method, it work this time, callbacks are working but still no sound play. I will make a simple test program to test it alone.

**Comment by Jegqamas** [comment]
It works !!
I made some tests, found out that i needed to change the byte order in the sound data, it looks like SDL always accept MBS, not LBS even though i change the format in the specs.
Anyway, the callback issue is fixed and sound is work. Thank you very much for the help and for this awesome library 🥇 
Here is the working source: https://www.dropbox.com/s/isvtmwlk4jgxnf9/mynessdlsource.zip?dl=0
Also, the final version will be available to download and use here: http://sourceforge.net/projects/mynes/

**Comment by flibitijibibo** [comment]
Cool, glad it works now.

**Comment by matwin** [comment]
FYI

Hi, I have the same issue like Jegqamas. On Linux i got sound with SDL_OpenAudio and the callback with SDL 2.0.8, but on Windows it doesn't work. I test a little around and found out that the last dll version that works (On Windows with Sound) is SDL 2.0.4.

**Comment by flibitijibibo** [comment]
Set `SDL_AUDIODRIVER=directsound` before initializing SDL_INIT_AUDIO and see if that fixes it; if so make a C version of the problem and file it on the Bugzilla:

https://bugzilla.libsdl.org/

**Comment by matwin** [comment]
You're right, it works with the environment variable.

Thank you!
