### ISSUE TITLE
sdl2_gfx

### ISSUE THREAD

**Issue by jackmott** [flibitijibibo/SDL2-CS#113]
Any reason we can't add bindings to gfx?  Or just nobody has done it yet?

**Comment by flibitijibibo** [comment]
Nobody's done it, I think. Look around the GitHub network and see if someone hasn't done this already, wouldn't surprise me if someone made it and never sent it back.

**Comment by flibitijibibo** [comment]
Closing due to old age, but as an FYI I would definitely merge a patch that added SDL2_gfx.
