### ISSUE TITLE
how to get started with .net standard?

### ISSUE THREAD

**Issue by AdmiralSnyder** [flibitijibibo/SDL2-CS#115]
i thought i do a new .net standard library to play around with sdl.
Found the sdl packages and this package on nuget, installed it.
But: i cannot see the SDL2 namespace anywhere. Is there something i missed? Is something more required? Is .net standard not an option (you have a commit saying the opposite)? If not: how do you suggest platform independence? Or is the nuget package simply too old?

if you give me a hint or two, i will gladly write something up for the readme.

**Comment by flibitijibibo** [comment]
There are no NuGet packages for SDL2#, any packages you see are unauthorized and potentially malicious.

To build the .NET Standard version, clone the repository and add SDL2-CS.Core.csproj to your VS solution.

**Comment by AdmiralSnyder** [comment]
there is this nuget-package from june of last year:
https://www.nuget.org/packages/SDL2-CS/2.0.0
the author's name is flibitijibibo - that's you, right?
if not, you might want to report abuse...

are there plans to build a nuget package?

**Comment by flibitijibibo** [comment]
That's me, but the owner appears to be "iwandi". Not sure if I can report a mirror, but I can definitely tell people not to download it.

There are no plans for official NuGet packages. 4 C# files a binary package does not make, and NuGet does not support source distributions as it really should.
