### ISSUE TITLE
SDL2-CS could not run on dotnet core environment

### ISSUE THREAD

**Issue by ysdafa** [flibitijibibo/SDL2-CS#117]
microsoft corefx and coreclr not support DllMap feature,
How to workaround as the issue mentioned in https://github.com/dotnet/coreclr/issues/930?
Thank you

**Comment by flibitijibibo** [comment]
As the issue notes, this can be worked around by using AssemblyLoadContext.LoadUnmanagedDll:

https://github.com/dotnet/coreclr/issues/930#issuecomment-99333437

**Comment by ysdafa** [comment]
have no authority to modify coreclr.
Is there other solution? 
Want to adopt to Samsung Tizen OS which include dotnet core 2.0 engine.

**Comment by flibitijibibo** [comment]
I think you just implement that class and push it somehow (like you would a Binder for a Serializer) but I don’t know what that process is exactly. If this is Tizen only i guess you could just rename nativeLibName in SDL2.cs but I would read up on AssemblyLoadContext to see what it is they expect you to do here.

**Comment by ysdafa** [comment]
Thank you anyway.
just rename nativeLibName in SDL2.cs works locally, but if want to public the change to this github for Tizen developer, which is not good solution.

**Comment by flibitijibibo** [comment]
Welcome to life with .NET Core, I guess.

See if you can figure out AssemblyLoadContext but either way this is a Core issue, not SDL2#’s. Any change we would make wouldn’t help other libs and probably would introduce conflicts between various projects. This is one of those situations where they really REALLY didn’t think about the existing ecosystem.

**Comment by qmfrederik** [comment]
An alternative for dllmap in .NET Core is supposed to the the `NativeLibrary` class, as described in dotnet/corefx#17135. If you think that could be useful, can you please upvote that issue? Thanks!

**Comment by flibitijibibo** [comment]
Wrote my comment in the FNA thread, TL;DR stop wasting my time and add dllmap to Core.

**Comment by flibitijibibo** [comment]
Not really, no. But I expect to see it added to .NET Core before dllmap, because why not.
