### ISSUE TITLE
How to use IntPtr with SDL_Surface structure type ?

### ISSUE THREAD

**Issue by MaximilienLIX** [flibitijibibo/SDL2-CS#118]
Hello, i want to create an SDL_Surface but, function like SDL_GetWindowSurface return a IntPtr.

`SDL_Surface surface = SDL.SDL_GetWindowSurface(window);
 SDL.SDL_FillRect(screenSurface, null, SDL.SDL_MapRGB(screenSurface->format, 0, 0, 0));
`
But i have an error with SDL_FillRect because this function take IntPtr and not SDL_Surface type.

How can i solve this ? I don't understand the commentary in SDL2.cs
`/* IntPtr refers to an SDL_Surface*, window to an SDL_Window* */`

Thank you

**Comment by flibitijibibo** [comment]
Change the type of `surface` in your example to IntPtr and it should work after that. Note that you’ll need to cast to SDL_Surface* using an `unsafe` keyword and use that cast variable to get `->format`.

**Comment by flibitijibibo** [comment]
Closing due to old age but AFAIK I answered this...
