### ISSUE TITLE
Add bindings for the SDL_AUDIODEVICEADDED and SDL_AUDIODEVICEREMOVED events.

### ISSUE THREAD

**Issue by holmak** [flibitijibibo/SDL2-CS#120]
Patch is attached. I tried to match the existing style as much as possible.

[audiodeviceevent.patch.txt](https://github.com/flibitijibibo/SDL2-CS/files/1533591/audiodeviceevent.patch.txt)

**Comment by flibitijibibo** [comment]
Ha, did I really add the event enums but not the actual struct? Go me...

Anyway, just pushed the patch, thanks for the fix!

https://github.com/flibitijibibo/SDL2-CS/commit/64e2a93d55fba6ca42412ece3d2c143479ed290c
