### ISSUE TITLE
SDL_CreateTexture doesn't accept SDL_TextureAccess enum without cast

### ISSUE THREAD

**Issue by JoaquinsVoid** [flibitijibibo/SDL2-CS#121]
Hi! Just giving SDL2-CS a test run.

SDL_CreateTexture doesn't accept a SDL_TextureAccess enum item without cast. You aparently need to do it like this:
`RenderTarget = SDL.SDL_CreateTexture(Renderer, SDL.SDL_PIXELFORMAT_RGBA8888, (int)SDL.SDL_TextureAccess.SDL_TEXTUREACCESS_TARGET, Width, Height);`

Is that deliberate?

**Comment by flibitijibibo** [comment]
Does adding `: int` to this line fix it?

https://github.com/flibitijibibo/SDL2-CS/blob/master/src/SDL2.cs#L1758

**Comment by JoaquinsVoid** [comment]
Nope.

**Comment by flibitijibibo** [comment]
Very well... So yeah, it's deliberate in the sense that C# can't into enums. I acknowledge that it's ugly but we'll have to pin the blame on C# for making enums so unpleasant to use...

**Comment by JoaquinsVoid** [comment]
Roger Roger

**Comment by JoaquinsVoid** [comment]
Any downsides to replacing the enum with:
```
public static class SDL_TextureAccess
{
   public static int SDL_TEXTUREACCESS_STATIC = 0;
   public static int SDL_TEXTUREACCESS_STREAMING = 1;
   public static int SDL_TEXTUREACCESS_TARGET = 2;
}
```
It's getting resolved at compile time either way, right?

**Comment by flibitijibibo** [comment]
It looks the same in source code but it's not exactly the same as a real enum. A good way to compare is to compile both ideas as DLLs, build an exe referencing one, then swap out the other. Both the runtime results and the IL will probably be different, the latter possibly in really interesting ways.

**Comment by JoaquinsVoid** [comment]
Right, OK.
