### ISSUE TITLE
Typo in SDL_MouseWheelDirection

### ISSUE THREAD

**Issue by bplu4t2f** [flibitijibibo/SDL2-CS#122]
SDL_MouseWheelDirection.SDL_MOUSEHWEEL_NORMAL
should be
SDL_MouseWheelDirection.SDL_MOUSEWHEEL_NORMAL

It is correct in the official SDL headers.

However fixing that is technically a breaking change, so I don't know how you want to handle this.

**Comment by flibitijibibo** [comment]
Can't imagine it breaking much other than compiles, and 2 characters isn't so bad!

https://github.com/flibitijibibo/SDL2-CS/commit/ed4838b75dadbdfcef4c23edb0c607c38d7237a2
