### ISSUE TITLE
How can I create window?

### ISSUE THREAD

**Issue by Kokosso** [flibitijibibo/SDL2-CS#124]
I know,  I should create object "window", but object "SDL" hasn't type "window"

**Comment by flibitijibibo** [comment]
SDL_CreateWindow:

https://wiki.libsdl.org/SDL_CreateWindow

https://github.com/flibitijibibo/SDL2-CS/blob/master/src/SDL2.cs#L1066

**Comment by Kokosso** [comment]
@flibitijibibo sorry for my stupid question. Thanks for the best wrapper.

**Comment by flibitijibibo** [comment]
No worries, hope it works well!
