### ISSUE TITLE
OSX / Ubuntu support?

### ISSUE THREAD

**Issue by Krakean** [flibitijibibo/SDL2-CS#127]
Hello
Is SDL2-CS supports OSX/Ubuntu?
If it is not, may be it can be possible via adding support for .NET Core 2.0 and adjusting nativeLibName .dll/.so/.dylib depending on platform?

**Comment by flibitijibibo** [comment]
The library is/was written on Linux and was originally designed for Linux/macOS support. Windows is actually the closest to a second-class citizen for us!
