### ISSUE TITLE
Mixer init enum wonky?

### ISSUE THREAD

**Issue by JoaquinsVoid** [flibitijibibo/SDL2-CS#128]
Trying to play MP3s
```
int retval = SDL_mixer.Mix_Init(SDL_mixer.MIX_InitFlags.MIX_INIT_MP3);
if(retval < 1) Debug.WriteLine(SDL.SDL_GetError());
```
Result
`Failed loading libmodplug-1.dll: The specified module could not be found.`

Change to MIX_INIT_OGG, result:
`MP3 support not available`

So, I'm guessing there are two things happening. The entries are swapped, and mpg dll isn't being loaded.

The libmpg123-0 dll is in the binary folder along with SDL2_mixer v2.0.2. I figured SDL_mixer would hook it up automatically.

**Comment by JoaquinsVoid** [comment]
Here's them in SDL_Mixer.h

```
typedef enum
{
    MIX_INIT_FLAC   = 0x00000001,
    MIX_INIT_MOD    = 0x00000002,
    MIX_INIT_MP3    = 0x00000008,
    MIX_INIT_OGG    = 0x00000010,
    MIX_INIT_MID    = 0x00000020
} MIX_InitFlags;
```

**Comment by flibitijibibo** [comment]
Looks like there was a pretty big desync at this commit, which appears to break the 2.0 API even... someone should probably report this:

https://hg.libsdl.org/SDL_mixer/rev/92882ef2ab81

For now SDL2# will sync with the latest tag:

https://github.com/flibitijibibo/SDL2-CS/commit/821c6aaf4910020f2811c9a8878f604729c4496c

**Comment by JoaquinsVoid** [comment]
For the record, I can't seem to make SDL_Mixer work with either ogg or mp3. Tried v2.0.0 to 2.0.2. I think, basically that the binary release doesn't actually support these formats! Seems weird that no one else has noticed though. Or maybe everyone builds their own dlls?

**Comment by flibitijibibo** [comment]
Try a native build to see if it works in plain C, and if it's still not working there you may want to file it on the Bugzilla.

**Comment by JoaquinsVoid** [comment]
I'm not setup to build C on windows, so I'll just skip music for now.
I might give it a go when I get a Ubuntu VM up and running. 
(Using core with VSCode btw. Aside from this, it works great.)

**Comment by JoaquinsVoid** [comment]
Update: Tried SDL_Mixer 2.0.3 pre-release build and it works. Though the format support DLLs has to go in the project root folder rather than the bin folder where the SDL_Mixer dll is. (Perhaps this can be remedied with a configuration file somewhere, the dotnet/core environment is still new to me.)
