### ISSUE TITLE
Any examples/tutorials? 

### ISSUE THREAD

**Issue by se5a** [flibitijibibo/SDL2-CS#131]
Just to get started? I'm not quite familiar enough with C to just go off the basic SDL2 tutorials out there, not quite sure where to start. I got a window to flick up and almost instantly disappear, so I guess that's something.  
I'm mostly familiar with the mvvm xaml WPF and it's ilk style of UI, with it's databinding etc, not sure how SDL does things.

**Comment by flibitijibibo** [comment]
SDL just gives you a window and, if you ask for it, a graphics context. Everything else has to be done entirely on your own, including UI elements and even OpenGL entry points! If you don't know the basics of OpenGL programming this probably isn't for you unless your intent is to learn graphics programming and not just drop in a different UI library.

For UI I strongly recommend looking at [ImGui](https://github.com/ocornut/imgui), and by extension, [ImGuiCS](https://github.com/0x0ade/ImGuiCS).

I also strongly recommend learning C/C++ basics; at the very least you want to learn about pointers and how they work, as SDL2# makes a deliberate effort to give developers an identical API surface, so if you're not familiar with native code, it will be very difficult to use and understand (and OpenGL will also be difficult to learn, if you're not already familiar with it). But once you're comfortable with *pointers/&references, it is very easy to translate C tutorials to C# as the APIs are identical in every way C# allows.

**Comment by se5a** [comment]
Ah I see, I thought it had some basic UI, I'll look at ImGuiCS. 
I've been wanting to learn some lower level stuff but been putting it off, maybe it's time to bite the bullet.
I was looking at these tutorials: http://lazyfoo.net/tutorials/SDL/index.php
and roughly following along, one problem I had though is in some function parameters they're passing null, for example: ```SDL_FillRect( screenSurface, NULL, SDL_MapRGB( screenSurface->format, 0xFF, 0xFF, 0xFF ) ); ```  
Is using ```IntPtr.Zero``` the correct translation here?

**Comment by flibitijibibo** [comment]
>Is using IntPtr.Zero the correct translation here?

Yep! That's one of the nastier parts of the translation to C#; the `ref` keyword isn't compatible with null references so we had to make lots and lots of overloads to allow sending `IntPtr.Zero`.

**Comment by se5a** [comment]
I checked out ImGuiCS and it looks like it could be exactly what I'm after for the UI side of things. 

one of the things I'm trying to accomplish is 'drawing' a 2d map of a solar system, in my previous attempts using a reactive UI (which has caused me all sorts of headaches, hence looking at SDL and instant mode guis) I did on eto.forms version of winforms/wpf canvas: 
![pulsarsystemmap](https://user-images.githubusercontent.com/1490538/39572658-2ce77244-4f24-11e8-95b7-6e9277bac191.png)
 The fading 3/4 orbit lines I was particularly proud of, once I'd figured out some of the dumb bugs I had when doing highly elliptical stuff, and finding a specific point at a given angle. 
How would be the best way to do this in SDL? do I need to go full OpenGL or can I get away with SDL_Render and expanding on that? it looks like SDL only has lines and not arcs which I'd need, but I did see a library which expands on that which I can maybe convert some of the functions there to do what I'm after: http://www.ferzkopp.net/Software/SDL2_gfx/Docs/html/index.html

I'd want to do mousewheel zoom and grab and drag around panning etc as well, and implement click selection and right click menus bringing up some ImGuiCS menus on some objects too, but 3d stuff would be out of scope. 


One other thing I didn't figure out when I was playing with SDL_FillRect was getting format from the screenSurface pointer. I tried converting the pointer to the object but that seemed rather complex (and I didn't quite manage to do it either) I figure there must be a simpler way...

**Comment by se5a** [comment]
Ah cool, thanks, I'll give that a try.

**Comment by flibitijibibo** [comment]
Going to close this since the original question seems to be answered, but feel free to keep using this thread if you need it.

**Comment by se5a** [comment]
all good, thanks.
Am I going to want to do this inside an ImGuiCS window or do an ImGuiCS window inside some SDL window, or some other thing?

**Comment by flibitijibibo** [comment]
CC'ing @0x0ade, not sure how that library is set up so it could be either or.

**Comment by se5a** [comment]
I'll ask on his issues

**Comment by 0x0ade** [comment]
ImGuiCS' SDL2 backend ships with a [`SDL2Window`](https://github.com/0x0ade/ImGuiCS/blob/master/ImGuiSDL2CS/src/SDL2Window.cs) and [`ImGuiSDL2CSWindow`](https://github.com/0x0ade/ImGuiCS/blob/master/ImGuiSDL2CS/src/ImGuiSDL2CSWindow.cs) classes, which your own window class can extend from, just like the [example "game" window.](https://github.com/0x0ade/ImGuiCS/blob/master/ImGuiSDL2CS-Example/src/YourGameWindow.cs)

@se5a I assume this issue now continues in https://github.com/0x0ade/ImGuiCS/issues/10?
