### ISSUE TITLE
No SDL_UpdateRect Method?

### ISSUE THREAD

**Issue by boonyachengdu** [flibitijibibo/SDL2-CS#138]
How can I change the ttf's Location to show?

**Comment by boonyachengdu** [comment]
[DllImport(nativeLibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void SDL_UpdateRect(IntPtr screen, int x, int y, int w, int h);

**Comment by flibitijibibo** [comment]
UpdateRect is an SDL 1.2 function and has since been removed. You probably want this:

https://wiki.libsdl.org/MigrationGuide

**Comment by flibitijibibo** [comment]
I think I answered this...
