### ISSUE TITLE
Potential memory leak when drop events are pumped?

### ISSUE THREAD

**Issue by TheMostCuriousThing** [flibitijibibo/SDL2-CS#147]
It doesn't seem that the `char` memory allocated for [non-null] `SDL_DropEvent.file`s is ever freed, and `SDL_free` is internal.

I don't know of any way to automate testing of file drag-and-drop, so I'm not sure if there is even memory leakage.

**Comment by flibitijibibo** [comment]
This is indeed a bug - the fastest way to fix this is make SDL_free public, though we'll need to explain why it's just free that's public and not malloc as well.

**Comment by TheMostCuriousThing** [comment]
It could also be wrapped in a property, e.g.

```
[StructLayout(LayoutKind.Sequential)]
public struct SDL_DropEvent
{
    public SDL_EventType type;
    public UInt32 timestamp;
    public IntPtr file; /* char* filename, to be freed */
    public UInt32 windowID;

    public string filePath
    {
        get
        {
            string f = Marshal.PtrToStringAnsi(file);
            SDL_free(file);
            return f;
        }
    }
}
```

**Comment by flibitijibibo** [comment]
Thought about this and a better way to do this might be to expose the UTF8 helpers. That way users can just call UTF8_ToManaged(evt.file, true) which will get the proper string while also freeing it, without exposing SDL_free specifically.

I'm doing an FNA update this week, so I can take a look at this at the same time if someone else doesn't beat me to it.

**Comment by flibitijibibo** [comment]
https://github.com/flibitijibibo/SDL2-CS/commit/65d719a058a0b296feb7de7361422c5339fc11dd
