### ISSUE TITLE
Does not work SDL_GL_GetProcAddress

### ISSUE THREAD

**Issue by masums** [flibitijibibo/SDL2-CS#150]
SDL_GL_GetProcAddress  does not work with calling value glGetString.

**Comment by flibitijibibo** [comment]
Got any code?

**Comment by flibitijibibo** [comment]
The types in this sample are really vague - for all I know the problem is with UTF8 conversion. Step through SDL_GL_GetProcAddress and it should go through UTF8_ToNative, that function is what you care about.

**Comment by flibitijibibo** [comment]
Took a wild guess and found the problem:

https://github.com/mono/SkiaSharp/blob/master/binding/Binding/GRGlInterface.cs#L9

This MarshalAs attribute is likely breaking everything. You’ll have to make your own DllImport for SDL_GL_GetProcAddress using the same attribute; we expect UTF8 and AFAIK SkiaSharp is the less accurate one in this case.

**Comment by masums** [comment]
Ok, forget about SkiaSharp. Just call SDL.SDL_GL_GetProcAddress("glGetString") from your library.  If it returns address then your library is ok.
