### ISSUE TITLE
SDL_OpenAudioDevice to create a simple beeper

### ISSUE THREAD

**Issue by veso266** [flibitijibibo/SDL2-CS#151]
Hi today I was trying to play around with SDL2 while trying to create a simple beeper

```C#
sing System;
using SDL2;
using System.Runtime.InteropServices;

namespace Beeper
{
    class BeepGenerator
    {
        //Audio

        IntPtr userdata[];
        SDL.SDL_AudioCallback Callback;
        

        SDL.SDL_AudioSpec srec;
        int pitch, wave_counter = 0;



        unsafe void SDL_AudioCallback(IntPtr userdata, IntPtr stream, int num_samples)
        {
            for (int position = 0; position < num_samples; position++)
            {
                //Generating one sample
                float sample = ((wave_counter / srec.freq) % 2 == 0) ? -0.5f : 0.5f;
                wave_counter += pitch * 2;

                //and put it into the buffer
                stream[position] = sample;
            }
        }
        public void AudioEngine()
        {
            srec.freq = 96000; 
            srec.format = SDL.AUDIO_F32SYS; 
            srec.channels = 1; 
            srec.userdata = userdata;
            srec.callback = SDL_AudioCallback;


            //Open Audio device
            uint dev = SDL.SDL_OpenAudioDevice(null, 0, ref srec, out srec, Convert.ToInt16(SDL.SDL_AUDIO_ALLOW_FREQUENCY_CHANGE));
            SDL.SDL_PauseAudioDevice(dev, 0);
        }
```

but I am stuck on how to generate data for it, it should call SDL_Audio Callback with userdata pointer and then feed this into srec.userdata if I understand this corecly, but I cannot seem to fed anything into InPtr

I know that this is probably my faulth not the library (which is great so Thanks for creating it) but I thought you could help me a bit to create this simple Beeper example

Thanks for Anwsering and Best Regards

**Comment by flibitijibibo** [comment]
You’ve got it mostly right, you just need to cast stream to a pointer value based on the sample type (in this case float*) and divide the callback’s len parameter by the type size. Just be sure not to use that sample generation though, because if I’m reading that right, the output will be... interesting...

Here are the docs for the callback: https://wiki.libsdl.org/SDL_AudioSpec#callback

**Comment by veso266** [comment]
hmm??

but how do I feed stream array? if I want to do it like this
```c#
stream[position] = sample;
```
compiler complains: C# Cannot apply indexing with [] to an expression of type 'IntPtr'

sorry but sometimes I just don't know what to do

**Comment by flibitijibibo** [comment]
You can cast IntPtr to real pointers:

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/pointer-types

As a warning, if pointers are scary to you, you may want to consider a higher-level audio library, as SDL is very very low-level compared to virtually every library out there (FAudio, OpenAL, etc).

**Comment by veso266** [comment]
I took that as a challenge and its always a good to learn something new

**Comment by flibitijibibo** [comment]
The len size is based on your format. You have 1-channel float sample frames, so it’s sizeof(float) * 1 bytes per frame.

**Comment by veso266** [comment]
OK, now I get nullReference exeption under streamPtr[position] = sample;
```c#
class BeepGenerator
    {

        public BeepGenerator()
        {
            SDL.SDL_InitSubSystem(SDL.SDL_INIT_AUDIO);
        }

        public void SDL_Delay(uint number)
        {
            SDL.SDL_Delay(number);
        }
        //Audio

        IntPtr userdata;
        IntPtr stream;

        SDL.SDL_AudioSpec srec;
        public int pitch, wave_counter = 0;

        unsafe SDL.SDL_AudioCallback SDL_Callback(IntPtr userdata, IntPtr stream, int num_samples)
        {
            for (int position = 0; position < num_samples; position++)
            {
                //Generating one sample
                float sample = ((wave_counter / srec.freq) % 2 == 0) ? -0.5f : 0.5f;
                wave_counter += pitch * 2;
                float* streamPtr = (float*)stream;
                //and put it into the buffer
                streamPtr[position] = sample;

            }
            return null;
        }

        public void AudioEngine()
        {
            srec.freq = 96000;
            srec.format = SDL.AUDIO_F32SYS; 
            srec.channels = 1; 
            srec.userdata = userdata;
            srec.callback = SDL_Callback(userdata, stream, sizeof(float));


            //Open Audio device
            uint dev = SDL.SDL_OpenAudioDevice(null, 0, ref srec, out srec, Convert.ToInt16(SDL.SDL_AUDIO_ALLOW_FREQUENCY_CHANGE));
            SDL.SDL_PauseAudioDevice(dev, 0);
        }
    }
```
a hard challange but would realy like to finish it, not just give up half way

and I am calling this from main like so
```c#
BeepGenerator beep = new BeepGenerator();
beep.AudioEngine();
beep.pitch = 440;
beep.SDL_Delay(500);
beep.pitch = 352;
beep.SDL_Delay(500);
```

**Comment by flibitijibibo** [comment]
Look at the post directly above yours. I _just_ said that the parameter is in bytes, NOT num_samples. That is the incorrect interpretation of that parameter. Rename it back to len and fix your usage of that variable.

**Comment by flibitijibibo** [comment]
Closing due to old age - as far as I can tell SDL2# works here.
