### ISSUE TITLE
SDL_JoystickEventState(SDL_ENABLE); does not automatically update Joysticks' states

### ISSUE THREAD

**Issue by GuardHei** [flibitijibibo/SDL2-CS#152]
Hi, I am recently using SDL as a plugin for Unity on Mac OSX. Basically, I have connected Switch Pro Controller to my MacBook using Bluetooth, and I tried to obtain the input data using the Joystick module. However, after setting `SDL_JoystickEventState(SDL_ENABLE); `, the data obtained using `SDL_JoystickGetAxis(IntPtr device, int axisIndex)` remains the same (it does not refresh). The problem disappeared after I manually call `SDL_JoystickUpdate()` every frame, the data got refreshed. It seemed that `SDL_JoystickEventState(SDL_ENABLE); ` has no use.

I have tried to log the response of `SDL_JoystickEventState(SDL_ENABLE); `, and it was 1, which was expected as the document said. So I think there should be a bug here.  

By the way, I had also initiated the subsystem SDL_INIT_VIDEO simply because the event system seemed to be initiated with the video module, but nothing changed. I'm using 2.0.9 version for mac, but I would say the problem still exists in the as old as 2.0.6 (I haven't tried any before this version).

I really appreciate your work for this c# bridge project, which helps me a lot, especially when dealing with cross-platform user input. I hope you guys can keep on this awesome project.

**Comment by flibitijibibo** [comment]
EventState is only useful if you have something that calls SDL_PumpEvents, which probably isn’t happening unless you’re somehow also using SDL’s video subsystem in a way that would implicitly call it. SDL_JoystickUpdate is the correct function to call.
