### ISSUE TITLE
SDL2_ttf.TTF_FontFaces(): return type issue

### ISSUE THREAD

**Issue by ru-ace** [flibitijibibo/SDL2-CS#155]
Hi! 
I think there is a mistake in return type of `SDL2_ttf.TTF_FontFaces()`
```cs
public static extern long TTF_FontFaces(IntPtr font);
```
```c
extern DECLSPEC long SDLCALL TTF_FontFaces(const TTF_Font *font);
```
`long` in c# is `Int64`
`long` in c is `Int32`
This is not a theoretical problem, because I paid attention to this after I received `8008139232616906753` (`0x6F22A03400000001`) as a return value.

Thanks!

**Comment by flibitijibibo** [comment]
This may have to be changed to IntPtr, where we ignore that Win64 sizeof(long) is still 4. It’s worked for me in the past but it should be tested first before it’s committed.

**Comment by ru-ace** [comment]
I only get this problem when running project in debug mode under VS Community 2017 (v15.9.7)
If I just run `.exe` from `bin/Debug` - I got `1`.
At the moment I solved this problem for myself by casting the return value to `int`
```cs
int fontfaces = (int)SDL_ttf.TTF_FontFaces(font); 
```

**Comment by flibitijibibo** [comment]
This one I'm not sure is really fixable because of Windows, and I dunno if breaking the ABI over it is necessary...

I'll add a comment warning Windows users but this may be out of our range here.
