### ISSUE TITLE
Missing SDL_RWFromFile

### ISSUE THREAD

**Issue by Marin-MK** [flibitijibibo/SDL2-CS#159]
Which would be quite useful for getting proper Audio support in that supports mp3 and midi as well (when using samples/chunks).

**Comment by flibitijibibo** [comment]
We do have it imported as an internal function, but only for functions in SDL and its libraries that are macro’d to use it (for example, SDL_LoadBMP.

I’ve thought about exporting it in the past but in practice it’s only really useful for those functions and nothing else. In general RWops doesn’t map well to C#, and in FNA we have something that really shows how awkward it can get:

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L1789

**Comment by flibitijibibo** [comment]
With the new exports in 2.0.10 this should now be looked at as part of #157.
