### ISSUE TITLE
Failed loading libpng16-16.dll

### ISSUE THREAD

**Issue by collinoswalt** [flibitijibibo/SDL2-CS#160]
in .Net core 2.1, When attempting to use `IMG_Load` on a `.png` image (this behavior exists for jpeg as well), the image fails to load and `SDL_GetError` returns `Failed loading libpng16-16.dll: The specified module could not be found.`

I've verified that SDL_Image.dll is loading correctly, and that the DLLs are all for the target platform (x64) Switching from PNG to BMP fixes the issue, but JPEG also does not work (returns the same error but with libjpeg).

This does not appear to be an issue with SDL2-CS, exactly; looking at the SDL2 Source, SDL uses `LoadLibrary` and `LoadPackagedLibrary` to dynamically load the DLLs at runtime. I'm not sure why, but running `dotnet run` yields the error, **but**, running `dotnet publish -r win-x64 --self-contained true` and then running the resultant .exe with the appropriate DLLs in the same directory yields **success**. I guess this has something to do with how native code finds libraries when using `LoadLibrary` and `LoadPackagedLibrary`, and what is has to do with the actual .exe running the program (`dotnet` vs. the published standalone `.exe`)

**Comment by flibitijibibo** [comment]
I would file this as a support issue with .NET Core (CoreCLR maybe?), if their DLL search path is busted they'll want to know.

**Comment by collinoswalt** [comment]
I think I agree. I was reluctant to post this here since it doesn't seem within the scope of the project, but since the issue seemed very specific to users of this library (or libraries of similar architecture), I figured it might be useful in the future for other users of SDL-CS (which I'm a huge fan of by the way!) If they ran into the same issue as me and could find my solution (self-contained publish).

**Comment by collinoswalt** [comment]
It appears that this is a known issue in Core CLI:

https://github.com/dotnet/coreclr/issues/24318#issuecomment-488149011

**Comment by flibitijibibo** [comment]
Cool, thanks for checking this out! I wasn't aware of it myself and I bet I'm going to see this from other users more than once, good to have a reference...
