### ISSUE TITLE
Proposal: Add SDL_Vulkan_GetInstanceExtensions overloading function. -From google translate.

### ISSUE THREAD

**Issue by ChinaChenMingQuan** [flibitijibibo/SDL2-CS#166]
```c#
[DllImport(nativeLibName, CallingConvention = CallingConvention.Cdecl)]
public static extern SDL_bool SDL_Vulkan_GetInstanceExtensions(
    IntPtr window,
    out uint pCount,
    IntPtr[] pNames
);
```
change to:
```c#
[DllImport(nativeLibName, CallingConvention = CallingConvention.Cdecl)]
public static extern SDL_bool SDL_Vulkan_GetInstanceExtensions(
    IntPtr window,
    out uint pCount,
    IntPtr[] pNames
);

public static SDL_bool SDL_Vulkan_GetInstanceExtensions(
    IntPtr window,
    out string[] names
)
{
    SDL_bool result;

    uint count;

    result = SDL_Vulkan_GetInstanceExtensions(window, out count, null);
    if (result != SDL_bool.SDL_TRUE)
    {
        names = null;
        return result;
    }

    IntPtr[] namesPtr = new IntPtr[count];

    result = SDL_Vulkan_GetInstanceExtensions(window, out count, namesPtr);
    if (result != SDL_bool.SDL_TRUE)
    {
        names = null;
        return result;
    }

    names = new string[count];

    for (uint i = 0; i < count; i++)
    {
        names[i] = UTF8_ToManaged(namesPtr[i]);
    }
    return SDL_bool.SDL_TRUE;
}
```

**Comment by flibitijibibo** [comment]
This is a lot more code than usual for a string conversion, but at the same time it’s a valid concern... @TheSpydog, did you run into this for VulkanDevice by chance?

**Comment by TheSpydog** [comment]
IMO this is something that application code should handle, not SDL2-CS. I'm quite not sure why you would want to convert the extension names to managed strings anyway, since you'll have to just convert them back to IntPtrs later to fill out Vulkan createInfo structs.

**Comment by flibitijibibo** [comment]
Makes sense. Sounds like it should remain as pointers and if the application wants to print the extensions they can call UTF8_ToManaged themselves (and properly deal with the managed array allocations going on, which is the most annoying part of this VK function...)

**Comment by ChinaChenMingQuan** [comment]
VulkanCore c# library github address: https://github.com/discosultan/VulkanCore.

My now use VulkanCore c# library. 

``` C#
VulkanCore.ApplicationInfo applicationInfo;

applicationInfo.ApiVersion = new VulkanCore.Version(1, 0, 0);
applicationInfo.ApplicationName = "My Project";
applicationInfo.ApplicationVersion = new VulkanCore.Version(1, 0, 0);
applicationInfo.EngineName = "Empty";
applicationInfo.EngineVersion = new VulkanCore.Version(1, 1, 0);

VulkanCore.InstanceCreateInfo instanceCreateInfo;

instanceCreateInfo.Next = IntPtr.Zero;
instanceCreateInfo.ApplicationInfo = applicationInfo;
instanceCreateInfo.EnabledLayerNames = null;

////////////////////////////////////////////////////////////////////////////    
// this core 
string[] exNames;
if (SDL_Vulkan_GetInstanceExtensions(sSDLWindow, out  exNames) != SDL.SDL_bool.SDL_TRUE)
{
    throw new System.Exception("...");
}

instanceCreateInfo.EnabledExtensionNames = exNames;
////////////////////////////////////////////////////////////////////////////       

VulkanCore.Instance sVkInstance = null;
sVkInstance = new VulkanCore.Instance(instanceCreateInfo);
```

**Comment by flibitijibibo** [comment]
Oh, so this is another library doing this to us... hm. I’m still unsure about this, since you’re typically supposed to enable just the extensions you want, not all of them at once. It also seems like a waste to do all this pointer conversion, as Spydog pointed out.

Can you ask the VulkanCore team about this to see if we can skip the conversion steps? It could be an important memory optimization if the extension list gets really long some day (as if it isn’t already).

**Comment by ChinaChenMingQuan** [comment]
I'm try going to ask questions VulkanCore. I closed this issues. If fail, I think about using low-level api vulkan library. -From google translate.
