### ISSUE TITLE
SDL2# and Android

### ISSUE THREAD

**Issue by log4x4** [flibitijibibo/SDL2-CS#173]
Hello everyone, i got problems with basic stuff on Android platform - i cant use the library because of missing .SO file (well, the error tells me that):
`System.DllNotFoundException has been thrown
libSDL2_mixer-2.0.so.0 assembly:<unknown assembly> type:<unknown type> member:(null)`

But in the same time i've got compiled libraries for Android in 

> %project_folder%/libs/armeabi-v7a/libSDL2_mixer-2.0.so
> %project_folder%/libs/x86/libSDL2_mixer-2.0.so

This libraries was renamed from "libSDL2_mixer.so" name, as it was compiled originally (i don't know if it is crucial or not). Also Build Action set for both files as `AndroidNativeLibrary`.

Simple code that i use to check if library working ok or not, not even playing any files:

> public static void PlayTestSound()
>         {
>             SDL2.SDL_mixer.Mix_OpenAudio(48000, SDL.AUDIO_F32LSB, 2, 4096);
>          }

Using Visual Studio v8.3.8 Mac Edition
Also some basic tutorial would be really great - how to do things with examples (i know, the original C/C++ tutorials around the internet exists, but still.. some of them involving `Mix_Chunk`, that is not presented(?) in this wrapper-project and it confuses me, because i am not experienced programmer. It might be helpful for others too.

**Comment by flibitijibibo** [comment]
Try keeping the original .so filenames without renaming anything and removing SDL2-CS.dll.config from the final output. You may have to add that last part as an automated post-build step.

**Comment by log4x4** [comment]
Actually i am using a Nuget-provided version of your package (SDL2-CS-Rolling is the name, i think). Also this was the way how i found your project too..
So i need to use version provided here? SDL2 was compiled from another source, i renamed back the original "libSDL2_mixer.so", but still error exist.

**Comment by flibitijibibo** [comment]
I do not have any NuGet packages, any packages suggesting they belong to me are not actually mine and you should notify the actual packager.

If you use the csproj directly you’ll see the app.config which shows the .so name that the runtime will look for as well as the documentation for the functions, including the part that explains what the IntPtrs represent, for example.

As for the native libraries I’m not sure what their naming convention is - I don’t target Android and don’t intend to, so I don’t have any experience with how they mangle Linux soname conventions. The important thing is that SDL2_mixer needs to find SDL2 as it was originally linked, so you definitely should not rename either file. Check the app.config and modify it as needed.

**Comment by log4x4** [comment]
Oh oh, i see. I thought that it is your package for some reason, excuse me then. I've checked the `csproj` files and yes, i see different bindings for win/linux/osx platforms and no Android there. I need to research about app.config files then.

But still - if i add necessary binding for Android platform - how can i use your project for my app? Do i need to make a package myself and add it to the project or what? And what is the difference between `SDL2-CS.Core` and `SDL2-CS`? 
For what i can tell - the Core version builds right away and there is not much settings that is used like in "regular" version. And how can i use that build?

Sorry for asking stupid questions - i am new to programming, so don't blame me too much :)

**Comment by flibitijibibo** [comment]
SDL2-CS is for .NET Framework, SDL2-CS.Core is for .NET Standard and Core.

To add the project, right click your solution and select Add Existing Project, then select whichever csproj is appropriate. Then you can add SDL2-CS as a project reference instead of a package reference, and everything should then work as it did before (except now you have source and can debug if necessary).

**Comment by log4x4** [comment]
Ok, will research on that, thank you. Also will try to add binding for Android and see, will it work or not.
In any case as you not targeting Android  - your project have no issue and i will close the ticket then.
