### ISSUE TITLE
Huge Memory Spike

### ISSUE THREAD

**Issue by Smeshur** [flibitijibibo/SDL2-CS#180]
I have a map of 1000x100 tiles that are 16x16 pixels.
I render the tiles and the buildings to a texture only when it needs to be updated (infrequent). 
I noticed a huge spike in memory usage, I looked into it for a while, but while I was just cleaning up little things as I went a long I noticed this.

The first method here has roughly 700mb impact on my memory usage, as opposed to the second.
This is with only 1 building in the list.
```C#            
foreach (var building in BuildingList)
{
        IntPtr bTexture = Building.TextureCache[building.TextureName];
        ....
        SDL.SDL_RenderCopy(renderer, bTexture , IntPtr.Zero, ref dest_rect);
}
```

```C#            
foreach (var building in BuildingList)
{
         ....
         SDL.SDL_RenderCopy(renderer, Building.TextureCache[building.TextureName], IntPtr.Zero, ref dest_rect);
}
```

Only a few things come to mind, but they all seem a little insignificant in comparison to the affect this has.

Can anyone shed some light and help me understand why this happens?

**Comment by kg** [comment]
In this case it's pretty important what the ```....``` actually is, because the rest of the code is functionally equivalent without it

**Comment by flibitijibibo** [comment]
Forgot to close this due to old age... without the load-bearing code we can’t diagnose the issue.
