### ISSUE TITLE
System.DllNotFoundException: 'Unable to load DLL 'SDL2.dll'

### ISSUE THREAD

**Issue by Shadowblitz16** [flibitijibibo/SDL2-CS#181]
after installing with nuget I get this...
```
System.DllNotFoundException: 'Unable to load DLL 'SDL2.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'
```

this is my code..
```cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SDL2;

namespace ZF
{
    public delegate void LoadDelegate();
    public delegate void StepDelegate();
    public delegate void DrawDelegate();
    public delegate void FreeDelegate();

    public static class Sys
    {

        internal static int    shader;
        internal static byte[] shaderPixels;

        internal static uint   w;
        internal static uint   h;
        internal static string name;


        public static LoadDelegate Load;
        public static StepDelegate Step;
        public static DrawDelegate Draw;
        public static FreeDelegate Free;

        public static void Init(uint w, uint h, string name)
        {
            Sys.w = w;
            Sys.h = h;
            Sys.name = name;


            SDL.SDL_Init(SDL.SDL_INIT_VIDEO);
            SDL.SDL_CreateWindow(name, SDL.SDL_WINDOWPOS_CENTERED, SDL.SDL_WINDOWPOS_CENTERED, (int)w, (int)h, SDL.SDL_WindowFlags.SDL_WINDOW_OPENGL);
            SDL.SDL_Delay(5000);
            SDL.SDL_Quit();
        }

    }
}
```

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZF
{
    class Program
    {
        static void Main(string[] args)
        {
            Sys.Init(256, 240, "Test");
        }
    }
}

```

**Comment by flibitijibibo** [comment]
>System.DllNotFoundException: 'Unable to load DLL 'SDL2.dll': The specified module could not be found.

This generally means that a DLL was not found; in verbose terms, it looked for a DLL called "SDL2.dll" and the OS was unable to find it. You can find a DLL named SDL2.dll here:

https://libsdl.org/download-2.0.php

**Comment by Shadowblitz16** [comment]
@flibitijibibo  is there any plans on embedding it inside the managed library?
I think it would be easier to set up and statically link it to custom engines.

if anything there should be info about it on the front github page and nuget package manager

**Comment by flibitijibibo** [comment]
No plans to embed the DLL.

I do not package SDL2# on NuGet so you will want to take it up with the packager. The README says that it wraps SDL2, which should suggest that it is not SDL2 itself. You will also find that the source repository and the csproj files do not contain SDL2.dll, which is another hint that you will need to get the binaries separately.

**Comment by Shadowblitz16** [comment]
@flibitijibibo  I'm not calling you a lair but the nuget package I downloaded has your name on it. 
do you share your github account with someone? 
if not someone might be publishing stuff under your name.

![image](https://user-images.githubusercontent.com/2453707/71328947-24f62800-24d4-11ea-82f1-88f8333e2899.png)

also I would highly recommend you embed the native dll at some point in the near future and use a package reference rather then just importing the SDL2-CS Folder. its kind of annoying to have it in the root of the project.

**Comment by flibitijibibo** [comment]
Please report that package, it is unauthorized and should not use my name.

Again, no interest in embedding, and I am happy with how native libraries are bundled for the platforms we target.

**Comment by Shadowblitz16** [comment]
there is like 3 SDL2-CS nuget packages with your name on them
so I guess I report them all? they are kinda the only ones on nuget.


also thats too bad that makes it harder on the user. 
you should really consider on making a more user friendly nuget package. 
its easier for you the developer to support it then someone else who has to download all the updated dlls and keep it up to date with your project.

**Comment by flibitijibibo** [comment]
Report any that do not name the actual author of the package. I wrote the software, but not the package. Any packager that does not name themself has a motivation for being anonymous and you should be very concerned about that.

I personally find NuGet despicable since, on top of there being absolutely no management, vetting, or even basic scanning of the packages whatsoever (like there is for real software repositories), source packages are not possible. Binary-only packages, particularly for a package system meant for developers, flawlessly misses the entire point by several galaxies. Until that’s fixed, Git submodules are unfortunately a far superior dependency manager for projects.

**Comment by nougator** [comment]
I have the same error but I have the SDL2.dll file
