### ISSUE TITLE
SDL.SDL.SDL_Method compared to c++'s sdl.sdl_function

### ISSUE THREAD

**Issue by Shadowblitz16** [flibitijibibo/SDL2-CS#183]
please remove the extra SDL_ prefix at the end its basicly the same as saying SDL.Method()
- this is hard to type out since we have to type SDL 2 times where in c++ you only need to do it once
- according to what it says on the repo it doesn't follow the rule of being as close to the c++ version as possible.
this is due to c++ version having 1 SDL namepsace and a SDL prefix where this CS version 1 SDL namespace and 2 SDL Prefixes

**Comment by flibitijibibo** [comment]
No.

**Comment by Shadowblitz16** [comment]
Ok Dude. Whatever

**Comment by TheSpydog** [comment]
If this is really important to you, you can put `using static SDL2.SDL` at the top of your C# file so you only have one "SDL" to write. Like this:
```
using static SDL2.SDL;

void Blah()
{
    SDL_CreateWindow(...);
}
```

**Comment by Shadowblitz16** [comment]
ok I will try it out thankyou
