### ISSUE TITLE
way to draw and fill ellipse?

### ISSUE THREAD

**Issue by Shadowblitz16** [flibitijibibo/SDL2-CS#184]
is there a way to draw and fill a ellipse?

**Comment by flibitijibibo** [comment]
SDL2_gfx would do that, but we don't have bindings for it in this repo: http://www.ferzkopp.net/wordpress/2016/01/02/sdl_gfx-sdl2_gfx/

**Comment by Shadowblitz16** [comment]
can bindings be added?
its really useful for rendering things

**Comment by flibitijibibo** [comment]
I think someone wrote them but never submitted them. I don't use SDL2_gfx so I'm not the right person to do the initial draft of SDL2_gfx.cs.

**Comment by Shadowblitz16** [comment]
oh ok well can you keep this open so they might see this issue?

**Comment by flibitijibibo** [comment]
They probably won't see this - you'll have to either write it from scratch or traverse the fork network to find it.

**Comment by Shadowblitz16** [comment]
dang ok I guess I will try to implement it in myself.
right now I am using sin and cos to draw lines to fill ellipse and other shapes

**Comment by flibitijibibo** [comment]
Closing due to old age, still no sign of this ever getting sent in.
