### ISSUE TITLE
convert SDL_Color[,] to IntPtr for SDL_CreateRGBSurfaceFrom?

### ISSUE THREAD

**Issue by Shadowblitz16** [flibitijibibo/SDL2-CS#185]
is this possible? I'm not sure what the IntPtr format is but I am trying to bind to lua and I would like top be able to draw a image from a 2d color table

**Comment by flibitijibibo** [comment]
No idea, StackOverflow might know though

**Comment by flibitijibibo** [comment]
Closing question due to old age
