### ISSUE TITLE
provide basic C# implementation for things that return IntPtr

### ISSUE THREAD

**Issue by Shadowblitz16** [flibitijibibo/SDL2-CS#186]
so right now everything seems to return a IntPtr which is unusable without knowing how to cast to the correct type.
for example the method  SDL_GetKeyboardState(out state); where state should be a uint[] however its a IntPtr.

also its doesn't really match the c++ implementation of sdl since IntPtr in C#  is basically a c++ void*.

I suggest that basic data types be implemented as return values and paramaters in methods.
so for example SDL_GetKeyboardState(out state); state would then return a uint[] allowing the user to easily know what it is and use it.

**Comment by flibitijibibo** [comment]
I’m okay with the functions as they are. I would need to see each function on a case-by-case basis for something like that; in particular, GetKeyboardState would only work with byte* because of the type size, and would still need to be a pointer to prevent duplicating data for no reason (meaning using the function at all would 100% require unsafe blocks on the application side).

**Comment by Shadowblitz16** [comment]
whats wrong with duplication if its just a byte[] a byte[] is basically the same thing as a byte* in c++?
I know its probably not exactly the same as c++ but its mostly the same thing

**Comment by flibitijibibo** [comment]
Mostly != Exactly. If I can avoid managed memory, I will - you can burn the memory in your application if you want, I won’t do it in the library.

**Comment by Shadowblitz16** [comment]
I can understand your reasoning 
however how do we operate on things?

C# is a managed language I don't think there is a good way to keep things unmanaged.

what about providing a overload for methods that take managed memory?
that way we can use marshal.ptrtostructure if we need to without having to convert back?

**Comment by flibitijibibo** [comment]
You will want to research the `unsafe` keyword as well as the `Marshal` class. Both of those cover the entirety of the non-opaque pointers covered by SDL2#.

**Comment by Shadowblitz16** [comment]
ok I will do that.
I'm closing this issue for now.
I might reopen it if I can't find a solution
