### ISSUE TITLE
Quick Marshallers for SDL_Surface, SDL_PixelFormat and more..

### ISSUE THREAD

**Issue by SourceSkyBoxer** [flibitijibibo/SDL2-CS#187]
Hello @flibitijibibo 
I give you suggestion for quick marshaller if they don't know how do they get non-used methods of IntPtr from SDL_Surface.
Check out my private glist for you. If you want have to make quick marshallers for SDL_Surface, SDL_Rect and more...
[Click here](https://gist.github.com/SourceSkyBoxer/012f6ee6f5a65c7273cfa2e0e9aaed5f)

Thank you for allowing of my idea. If you love "quick marshallers" than they will make easy. Why not?

I hope you accept my idea.

Best regards, Jens Eckervogt

**Comment by flibitijibibo** [comment]
```
            if (pf_ptr == IntPtr.Zero)
            {
                Console.WriteLine("Error: IntPtr shouldn't be null");
                Environment.Exit(0);
            }
```
```
                Environment.Exit(0);
```

Seems a bit extreme, don't you think...?

The idea is otherwise functional, but we don't provide helpers in the library unless it's absolutely 100% mandatory (UTF8 marshaling, for example).

**Comment by SourceSkyBoxer** [comment]
Okay no problem! I should remove Environment.Exit(0);

Thanks! I will respect you.
