### ISSUE TITLE
Reading embedded resources

### ISSUE THREAD

**Issue by TheRamsWay** [flibitijibibo/SDL2-CS#188]
Hi!
Is there a way to read files (fonts or images for example) from .NET embedded resources included from the .csproj file? These resources are accessed as Streams but SDL2# only seems to use file locations from strings or IntPtr.
Thanks,
Rams

**Comment by flibitijibibo** [comment]
You can fake an RWops that reads Streams - here's how we do it in FNA, for example:

https://github.com/FNA-XNA/FNA/blob/master/src/FNAPlatform/SDL2_FNAPlatform.cs#L2069
