### ISSUE TITLE
SDL_Metal_GetLayer

### ISSUE THREAD

**Issue by lithiumtoast** [flibitijibibo/SDL2-CS#190]
Some Metal functions are missing. See [`SDL_metal.h`](https://github.com/spurious/SDL-mirror/blob/ce16f9440ca838982f93bf948219fe70a09fd0fd/include/SDL_metal.h).

- [SDL_Metal_GetLayer](https://github.com/spurious/SDL-mirror/blob/ce16f9440ca838982f93bf948219fe70a09fd0fd/include/SDL_metal.h#L83)
- [SDL_Metal_GetDrawableSize](https://github.com/spurious/SDL-mirror/blob/ce16f9440ca838982f93bf948219fe70a09fd0fd/include/SDL_metal.h#L106)

**Comment by flibitijibibo** [comment]
These functions were added barely 10 hours ago: https://hg.libsdl.org/SDL/rev/aca267270368

We'll add them when 2.0.14 is out.

**Comment by flibitijibibo** [comment]
Closing in favor of #209, getting close!
