### ISSUE TITLE
Android and UWP support

### ISSUE THREAD

**Issue by demonixis** [flibitijibibo/SDL2-CS#191]
Hello,

I use your library in an Unity project for input only. It works great but know I would like to use it on Android and UWP. I took a look at the [app.config](), if I'm correct, I've to add a line for UWP and another for Android? If yes, where can I find the libraries for these platforms? I can probably compile the DLL for UWP, but no clue for Android. Have you already did that?

**Comment by flibitijibibo** [comment]
UWP will look something like this: https://github.com/FNA-XNA/FNA/wiki/Appendix-B:-FNA-on-Consoles#code-differences

Android is not and will not ever be supported by SDL2#, so you’ll have to do your own research for that target.

**Comment by demonixis** [comment]
Thank you for your time. I'll try to do something with UWP first.
