### ISSUE TITLE
SDL_audio

### ISSUE THREAD

**Issue by larsbrinkhoff** [flibitijibibo/SDL2-CS#193]
Hello,

I have a need to use the SDL_audio APIs.  Would it be possible to add those?

**Comment by flibitijibibo** [comment]
I believe they are already present, in the region named SDL_audio.h. If anything is missing they can be added in.

**Comment by larsbrinkhoff** [comment]
Thank you.  I was trying to use the type SDL_AudioDeviceID but I see now it's just an unit.
