### ISSUE TITLE
 SDL_MixAudio 

### ISSUE THREAD

**Issue by Xhone** [flibitijibibo/SDL2-CS#195]
Hi @flibitijibibo :
    I use the SDL_MixAudio method in SDL_AudioCallback(IntPtr userdata, IntPtr stream, int len),

             byte[] dst = new byte[len];
             byte[] src = new byte[len];
             Marshal.Copy(stream, dst, 0, len);
             SDL.SDL_MixAudio(dst, src, (uint)len, SDL.SDL_MIX_MAXVOLUME);

 I don't know whether it works?

**Comment by flibitijibibo** [comment]
The `new`s are a bit of a worry, but no matter how you end up mixing sound, the important part is that the stream is directly written to. You most likely want:

```

         byte[] dst = new byte[len]; /* Allocate this somewhere else */
         byte[] src = new byte[len]; /* Yup, this too */
         Array.Clear(dst);
         SDL.SDL_MixAudio(dst, src, (uint) len, SDL.SDL_MIX_MAXVOLUME);
         Marshal.Copy(dst, 0, stream, len);
```

**Comment by Xhone** [comment]
As you said,I modify the code,but there is no sound to output,i think the src and dst that i misunderstand,

the audio decoder data:

`Queue<byte[]> m_audioQueue= new Queue<byte[]>();
 out_buffer_size_audio = ffmpeg.av_samples_get_buffer_size(null, out_channel_nb, frame_Audio->nb_samples, out_sample_fmt, 1);
                               
 int dst_nb_samples=(int)ffmpeg.av_rescale_rnd(ffmpeg.swr_get_delay(swrCtx_Audio, frame_Audio->sample_rate) + frame_Audio->nb_samples,
out_sample_rate, (long)out_sample_fmt, 
AVRounding.AV_ROUND_INF);

 ffmpeg.swr_convert(swrCtx_Audio,
 &out_audio_buffer, 
dst_nb_samples, (byte**)&frame_Audio->data,
 frame_Audio->nb_samples);

 lock (_isSDLAudio)
 {
           byte[] audioFrameBytes = new byte[out_buffer_size_audio];
            Marshal.Copy((IntPtr)(void*)out_audio_buffer, audioFrameBytes, 0, out_buffer_size_audio);
            if (m_audioQueue != null)
                m_audioQueue.Enqueue(audioFrameBytes);
 }`

the SDL_AudioCallback method:
 `void SDL_AudioCallback(IntPtr userdata, IntPtr stream, int len)
 {
            SDL.SDL_RWFromMem(stream, len);

            if (m_audioQueue.Count <= 0)
            {
                for (int i = 0; i < len; i++)
                {
                    ((byte*)stream)[i] = 0;
                }
                return;
            }
            if (m_audioQueue == null)
                return;

            lock (_isSDLAudio)
            {
                byte[] data = m_audioQueue.Dequeue();

                if (data.Length <= 0)
                    return;

                len = (len > data.Length ? data.Length : len);
                if (len > 0)
                {
                    byte[] src = data;
                    byte[] dst = new byte[len];
                    SDL.SDL_MixAudio(dst, src, (uint)len, SDL.SDL_MIX_MAXVOLUME);

                    Marshal.Copy(dst, 0, stream, len);
                }
                else
                {
                    byte[] temp = new byte[len];
                    Marshal.Copy(temp, 0, stream, len);
                }              
            }
}`

**Comment by flibitijibibo** [comment]
The Mix call isn’t needed here - you can copy the source data directly, the volume clipping probably won’t be of any use.

**Comment by Xhone** [comment]
Hi @flibitijibibo:
    If i want to change the volume,what should i do?

**Comment by flibitijibibo** [comment]
That would be where MixAudio is appropriate - be sure your format is correct though:

https://wiki.libsdl.org/SDL_MixAudioFormat

**Comment by Xhone** [comment]
Hi @flibitijibibo:
    Thank you so much,it works.
