### ISSUE TITLE
Problem with SDL_GL_GetProcAddress is not working?

### ISSUE THREAD

**Issue by DeafMan1983** [flibitijibibo/SDL2-CS#196]
Hello dear,
I have problem with SDL_GL_GetProcAddress()
I looks not working now.
Since I have readden your old github it got working now. It doesn't work now.
I really don't understand why does it happen?
Screenshot looks like failure:
![image](https://user-images.githubusercontent.com/57066679/83334466-0ed06d00-a2a7-11ea-8005-e2fa3df9e0ed.png)
If SDL_GL_GetProcAddress won't work them I should use SDL_LoadObject and SDL_LoadFunction?

I will show you my code for Example as Engine.cs and GL.cs with Program.cs

Engine.cs
```
using System;
using static SDL2.SDL;

namespace GameStudio
{
    public class Engine
    {
        protected Engine()
        {
            // Constructor ( ctor() )
        }

        ~Engine()
        {
            j_isRunning = false;
        }

        protected IntPtr j_window;
        protected IntPtr j_renderer;
        protected static readonly Engine j_instance;
        private bool j_isRunning;

        public static Engine Instance
        {
            get
            {
                return j_instance ?? new Engine();
            }
        }

        public bool IsRunning()
        {
            return j_isRunning;
        }

        public bool Init()
        {
            if (SDL_Init(SDL_INIT_EVERYTHING) != 0)
            {
                Console.WriteLine("Error: SDL2 Couldn't initalize " + SDL_GetError());
            }
            else
            {
                Console.WriteLine("Success: SDL Initalizes completly.\n");
            }

            return (j_isRunning == false) || j_isRunning;
        }

        public void Handle(SDL_Event evt)
        {
                ....
        }

        public void Render()
        {
                ...
        }

        public void Update(double sec)
        {
                ...
        }

        public void CleanUp()
        {

            if (j_window != IntPtr.Zero && j_renderer != IntPtr.Zero)
            {
                SDL_DestroyRenderer(j_renderer);
                SDL_DestroyWindow(j_window);
            }

            SDL_Quit();
        }
    }
}
```

GL.cs
```
using System;
using System.Runtime.InteropServices;
using static SDL2.SDL;

namespace GameStudio
{
    ....
    public enum StringName
    {
        Vendor = 0x1F00,
        Renderer = 0x1F01,
        Version = 0x1F02,
        Extensions = 0x1F03,
    }

    public static class GL
    {
        private static T LoadFunction<T>(string function, bool throwIfNotFound = false)
        {
            var ret = SDL_GL_GetProcAddress(function);

            if (ret == IntPtr.Zero)
            {
                if (throwIfNotFound)
                    throw new EntryPointNotFoundException(function);

                return default(T);
            }
            return (T)(object)Marshal.GetDelegateForFunctionPointer(ret, typeof(T));
        }

        [UnmanagedFunctionPointer(CallingConvention.StdCall)]
        private delegate IntPtr je_getstring(StringName pname);
        public unsafe static string GetString(StringName pname)
        {
            je_getstring getstring = LoadFunction<je_getstring>("glGetString");
            return new string((sbyte*)getstring(pname));
        }

    }
}
```
Program.cs
```
using System;

namespace GameStudio
{
    class MainClass
    {
        static void Main(string[] args)
        {
            Engine engine = Engine.Instance;

            engine.Init();
            Console.WriteLine("OpenGL Version: " + GL.GetString(StringName.Version));

            while (engine.IsRunning())
            {
                engine.Render();

            }

            engine.CleanUp();
        }
    }
}
```
And it throws 2 errors of ArgumentExpection(). I have tried.. Like your OpenGL.cs in FNA = No working now. How do I resolve it. I am using Mono 5.20.1.19 and Ubuntu 20.04 with OpenGL 4.6 and AMDGPU. Why do I use old version of Mono because it is stable for mkbundle.

Thanks for answering :+1:

**Comment by flibitijibibo** [comment]
If you have the latest tip, this is what you want to step through:

https://github.com/flibitijibibo/SDL2-CS/blob/master/src/SDL2.cs#L1777

We're currently using this with FNA and it works for us.

**Comment by DeafMan1983** [comment]
Thanks but It doesn't work for me :/

It is really complicatedly. Can I have example simple function glGetString than How do I can get SDL_GL_GetProcAddress and I verify with try - catch statement. than It doesn't happen.
```
using System;
using System.Runtime.InteropServices;
using static SDL2.SDL;

namespace GameStudio
{
    public static class GL
    {
        public enum StringName
        {
            Vendor = 0x1F00,
            Renderer = 0x1F01,
            Version = 0x1F02,
            Extensions = 0x1F03,
        }

        [UnmanagedFunctionPointer(CallingConvention.StdCall)]
        private delegate IntPtr je_getstring(StringName pname);
        public static string GetString(StringName pname)
        {
            unsafe
            {
                je_getstring getstring = (je_getstring)Marshal.GetDelegateForFunctionPointer(SDL_GL_GetProcAddress("glGetString"), typeof(je_getstring));
                return new string((sbyte*)getstring(pname));
            }
        }
    }
}
```
I have always tried but no luck :(
It always trow error like exception.  I have tried since yesterday :( No success... :(

**Comment by flibitijibibo** [comment]
Stepping through the function doesn’t work?  It sounds like something is wrong with the UTF8 encode but we need to see what the bytes look like on your setup. Without any concrete data that shows the input variable is being converted incorrectly, it could be a bad graphics driver for all I know.

**Comment by DeafMan1983** [comment]
Yeah I have tried other way with libdl.so.2 and it looks no shows up.
![image](https://user-images.githubusercontent.com/57066679/83352563-96bc8280-a34c-11ea-85c5-01df399c5dcd.png)
I think Ubuntu 20.04's libGL.so has wrong UTF8 format. But I have already tried with AMDGPU and Mesa to re-installation... 

Thanks and sorry my bad English!

**Comment by flibitijibibo** [comment]
Ubuntu 20.04 seems to have a lot of graphics regressions this cycle - I’ve had other reports of regressions with existing games shipping versions prior to the UTF8 update. I would report this to Canonical if possible!

**Comment by DeafMan1983** [comment]
Hey my friend, I am sorry for longer waiting, I need close because I have downgraded to Ubuntu 18.04.4 and it seems working because UTF8 format was correct in Ubuntu 18.04.x ( but I don't test Ubuntu 19.04 )

I think sure that Ubuntu 20.04 has wrong UTF8 format. Maybe you should check MonoGame repository - why does Cra0zy or other MG Developers write easy without UTF8 Support?
