### ISSUE TITLE
[F# Support] : Rename SDL_EventType type attributes to SDL_EventType eventType

### ISSUE THREAD

**Issue by ykafia** [flibitijibibo/SDL2-CS#198]
As type is a protected keyword in F#, fields named `type` can't be called.
For consistency .NET language maybe `eventType` is a more suited name ?

**Comment by flibitijibibo** [comment]
We have a lot of stuff that depends on this name, but I have another idea - does adding another field below this one with the same type but different name fix it?

https://github.com/flibitijibibo/SDL2-CS/blob/master/src/SDL2.cs#L4827

**Comment by ykafia** [comment]
It fixes everything !

**Comment by flibitijibibo** [comment]
https://github.com/flibitijibibo/SDL2-CS/commit/a31694d145292adefa51c928179d86b408a63db4
