### ISSUE TITLE
How to get compiled TTF and Sound Libraries?

### ISSUE THREAD

**Issue by JimiIT92** [flibitijibibo/SDL2-CS#201]
Hi, sorry if this is a dumb question, but how can I compile the library files for SDL2_ttf and SDL2_mixer? Because I imported the SDL2-CS reference in my project, however if I try to render a text it says it doesn't find the module :/

**Comment by flibitijibibo** [comment]
https://www.libsdl.org/projects/SDL_ttf/
https://www.libsdl.org/projects/SDL_mixer/

**Comment by JimiIT92** [comment]
I see what you did there! Jokes aside, I know these, but these are for C++. I want to import them into a C# project, but if I just add the dll as a reference it says I can't
Essentially what I want is that they show up in the project like these
![image](https://user-images.githubusercontent.com/14943331/84951629-fe1a5680-b0f0-11ea-9b92-e4f89aaeede2.png)
For example for the Image library I got this folder structure
![image](https://user-images.githubusercontent.com/14943331/84951791-391c8a00-b0f1-11ea-8809-17713264f240.png)
in which I have the required files
By looking at the app.config file from SDL2-CS project I think these should be generated by the project itself. If not please help me figuring out why they shouldn't

**Comment by flibitijibibo** [comment]
SDL2# just imports from the native library and has no real functionality by itself. You will need to include the native libraries into your output for the functions to work.
