### ISSUE TITLE
Add 2.0.14 features

### ISSUE THREAD

**Issue by flibitijibibo** [flibitijibibo/SDL2-CS#209]
The release candidate is happening now, finally. The new export list is stupidly long:

https://hg.libsdl.org/SDL/file/default/WhatsNew.txt

I'm still out but if someone wants to beat me to this I can merge it in.

**Comment by flibitijibibo** [comment]
2.0.14 is now available.

**Comment by TheSpydog** [comment]
I’ll get right on this.

**Comment by flibitijibibo** [comment]
Excellent, I'll write in https://github.com/FNA-XNA/FNA/issues/340 as soon as this is ready. Will do an fnalibs update at the same time.
