### ISSUE TITLE
[Question] Segfault when calling SDL_GetWindowSurface, how to proceed?

### ISSUE THREAD

**Issue by Kangaroux** [flibitijibibo/SDL2-CS#211]
Original issue: https://github.com/OpenChartProject/OpenChart/issues/106

Tested on my desktop and laptop both running Ubuntu 20.04, same .NET version, same SDL2 version. The segfault occurs only on my desktop, and it happens the first time SDL_GetWindowSurface is called, so nothing has been drawn yet.

How should I proceed with debugging this?

**Comment by flibitijibibo** [comment]
Use debug symbols for your native SDL library and debug with GDB:

https://www.mono-project.com/docs/debug+profile/debug/#debugging-with-gdb

Note that Core is not supported on anything other than Xbox:

https://github.com/FNA-XNA/FNA/wiki/0:-FAQ#i-have-a-bug-when-running-on-net-core-and-

**Comment by Kangaroux** [comment]
Appreciate the fast reply, I'll start with those links. Thanks.
