### ISSUE TITLE
Is this the way to run Monogame/XNA games on GNU/Linux without X11?

### ISSUE THREAD

**Issue by vanfanel** [flibitijibibo/SDL2-CS#220]
Hi there,

Just discovered this project!
Since SDL2 has a nice KMSDRM backend now, show this wrapper allow XNA/Monogame games to run without X11? (As in: game runs on this, and in turn SDL2 runs on KMSDRM).

Thanks!

**Comment by flibitijibibo** [comment]
MonoGame does not use SDL2#. FNA does though.

A game could run SDL_VIDEODRIVER=kmsdrm but I haven't tried it myself. Either way, you're looking for SDL, not SDL2#.

**Comment by vanfanel** [comment]
@flibitijibibo 
I know SDL2 games can run with `SDL_VIDEODRIVER=kmsdrm`. In fact, I have SDL2 with only KMSDRM enabled, so they always run on KMSDRM (no X11).

So, this is for FNA games and Monogame is for XNA games?

**Comment by flibitijibibo** [comment]
Correct. By the way, SDL has a place for questions:

**Comment by vanfanel** [comment]
@flibitijibibo Sorry, but I don't have any SDL2 questions. In fact, I am an SDL2 developer (KMSDRM backend).

I am just trying to understand FNA and use it. My english may look strange sometimes, so maybe that was confusing.
