### ISSUE TITLE
[SDL_Joystick] [Windows?] Hat event accuracy

### ISSUE THREAD

**Issue by aleksandaratanasov** [flibitijibibo/SDL2-CS#51]
Hi!

I just discovered that the SDL2 C# wrapper doesn't handle the Joystick slider/hat events properly. The only hat-event that gets registered is the SDL_HAT_CENTERED. All the rest are just ignored. Throttle axis does not trigger and event at all. In order to determine if the issue lies in the SDL2 library for Windows or just in the wrapper for C# I created two mirrored projects in Visual Studio 2010 - one in VC++ 2010 and the other in C# 4.0. If you need the full code, I can provide it as an archive. Further I have tested all other buttons and axes and they are working flawlessly in both C# and VC++ in Windows.

Here is just the interesting part of the code that handles the Hat-event:

```
while (running)
{
    SDL.SDL_PollEvent(out sdlEvent);
    // Other joystick event handled here (JOYAXISMOTION,
    // JOYBUTTONDOWN, JOYBUTTONUP)
    if(sdlEvent.type == SDL.SDL_EventType.SDL_JOYHATMOTION)
    {
        switch(sdlEvent.jhat.hat)
        {
            case (byte)SDL.SDL_HAT_CENTERED:
                // We land only in this case
                Console.WriteLine("Hat : center");
                break;
            case (byte)SDL.SDL_HAT_UP:
                // We never land in this case
                Console.WriteLine("Hat : up");
                break;
            case (byte)SDL.SDL_HAT_RIGHTUP:
                // We never land in this case
                Console.WriteLine("Hat : right up");
                break;
            // . . . 
            case (byte)SDL.SDL_HAT_LEFTUP:
                // We never land in this case
                Console.WriteLine("Hat : left up");
                break;
        }
    }    
}
```

Since SDL.SDL_HAT_* are all just an enumeration replacing those with manually written 0,1,2,... doesn't change anything. I did that though to make sure that the enumeration isn't somehow incorrect leading to the fact that none of those cases (except CENTERED) are getting "hit" when entering the switch-block. I also checked their values by simply creating additional cases with 0,1,2,... and Visual Studio told me that there are already cases in the switch block that handle those.

If you need more feedback, I'll do my best to provide more information :)
Bye!

**Comment by flibitijibibo** [comment]
Closing due to old age. (This is almost a year old!)
