### ISSUE TITLE
SDL_PeepEvents() returning garbage event types

### ISSUE THREAD

**Issue by trsoluti** [flibitijibibo/SDL2-CS#69]
Great library!

I've created a wrapper library around yours at github/trsoluti/SDL2-CS-COP which implements PySDL's COP on top of your interface.

PySDL uses SDL_PeepEvents to get an array of events. I notice if I use that, SDL_QUIT is not being returned for Window Close on my Mac. However, it does work if I use SDL_PollEvent. Other events (such as key press) appear to be okay.

I'm worried that your definition of SDL_Event (the "ugly thing" using FieldOffsets) isn't the right size, causing some events in the array to be corrupt.

Thanks for looking into this...

Thomas O'Dell.

**Comment by flibitijibibo** [comment]
Closing due to old age.
