### ISSUE TITLE
TEXTINPUT and TEXTEDITING events behaving unexpectedly

### ISSUE THREAD

**Issue by Villermen** [flibitijibibo/SDL2-CS#70]
A few things I've noticed about these events. I have no idea if this is a bug in the binding or the library, but I'm starting here.

I read the expected behavior for these events from https://wiki.libsdl.org/SDL_TextInputEvent (the detailed explanation), but my findings are completely different.

First I'll give you the project I've used to check these events, because maybe the fault is on my part (then it should be clearly visible in the project): http://puu.sh/b4NVK/b52c26c35b.zip

The program behaves like StartTextInput is called from the start, so I'll have to manually call StopTextInput() to disable it.

The textediting event only occurs when the window loses focus, for whatever reason. It should occur everytime a relevant button is pressed to my knowledge.

The textinput event occurs every time I press a button (excluding modifiers). The event data will contain this character. It will not take into account my language's features like displaying é when I press ' and then e, but it will e.g. make it an uppercase character if I had shift pressed.

Here's a screenshot of the console output in a test-run of the project:
![http://puu.sh/b4OM9/4cb087e6d8.png](http://puu.sh/b4OM9/4cb087e6d8.png)

I have no idea how to make sense of these events now, but I'm pretty sure they are not working as expected.

Gr.Viller

**Comment by flibitijibibo** [comment]
Closing due to old age, though it sorta looks like this got solved anyway... client-side fun (thanks, marshaling).
