### ISSUE TITLE
[SDL2 Docs] Could we get some Sample Code?

### ISSUE THREAD

**Issue by Nixhatter** [flibitijibibo/SDL2-CS#71]
Could we get some sample code as a reference on how some C++ SDL code would look like in C#?

Like the tutorials section in LUA:
https://redmine.malikania.fr/projects/luasdl2/wiki

and similar in the python binding (site is down right now): 
https://pythonhosted.org/pysdl2-cffi

I got up to Tutorial 4 on [Lazy Foo's series](http://lazyfoo.net/tutorials/SDL/index.php) , which I could post but not sure if it was done correctly.

Examples of what I have trouble with, specifically surrounded by ** :

    IntPtr textSurface = SDL_ttf.TTF_RenderText_Solid(**gfont**, textureText, textColor);
                    //Get image dimensions
                    mWidth = **textSurface->w**;
                    mHeight =** textSurface->h**;

From [this](http://lazyfoo.net/tutorials/SDL/26_motion/index.php) tutorial.

As a side, thanks for the C# binding!

**Comment by flibitijibibo** [comment]
Closing due to old age.

At this point the best way to get docs would be for someone to port LazyFoo's stuff to C#/SDL2#, but that probably won't be done by me. There may be some things missing in SDL2# from the tutorials, and we can look at those features individually. Some things like the SDL_Surface may never get filled in entirely, but I'm sure there's one or two thing we've not written entry points for just yet.

**Comment by ThatOneCheetah** [comment]
I know this article is pretty old, but for people who still wonder how to access the structs using the IntPtrs you get; here's an extension that casts the IntPtr to a struct of type T:

```csharp
public static T Struct<T>(this IntPtr pointer)
{
    return (T)System.Runtime.InteropServices.Marshal.PtrToStructure(pointer, typeof(T));
}
```

Copy this in to any class in your project and include the namespace. `e.g. MyProject.Extensions`

To get `SDL_Surface` from `IntPtr` you would do like:
```csharp
SDL_Surface SurfaceStruct = SurfaceIntPtr.Struct<SDL_Surface>();
```

Which then allows you to access for example `SurfaceStruct.format`.
