### ISSUE TITLE
White noise with Mix_HookMusic

### ISSUE THREAD

**Issue by danellos** [flibitijibibo/SDL2-CS#85]
Hello,

I am almost certain I am doing something wrong, but I can't figure it out.

I am trying to play music with the SDL_mixer by buffering it through with a normal C# Stream. From the SDL_mixer docs, doing that would require me to use Mix_HookMusic. This is what my event handler looks like:

````C#
        Stream _input;
        byte[] _buffer = new byte[1024];
        bool _isPlaying;

        void Sound_MemMusicPlayer(IntPtr udata, IntPtr stream, int len)
        {
            if (_buffer.Length < len)
                _buffer = new byte[len];

            if (_isPlaying)
            {
                _input.Read(_buffer, 0, len);
            }
            else
            {
                Array.Clear(_buffer, 0, len);
            }

            Marshal.Copy(_buffer, 0, stream, len);
        }
````

Which is being called like so somewhere in my class:
````C#
            _isPlaying = true;
            SDL_mixer.Mix_HookMusic(MemMusicPlayer, IntPtr.Zero);
````

I have verified that the Marshal.Copy is definitely copying through the byte array in the same way the docs depict in C here https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_60.html 

However, the sound comes through as gibberish white noise, no matter what file I test this with (mp3, ogg, flac).

Am I doing this wrong, or is there simply no way to get this done from C#? 

Thanks in advance!

**Comment by flibitijibibo** [comment]
My understanding is that HookMusic is meant to be for processing of a Mix_Music* playing, so that could be one possible issue.

As for the actual functionality, you may want to test this in C and see if the result is any different. The code looks right to me as well, but that's assuming what we're doing is right in any scenario. A couple variables I can't see from here are sample rates and bit depth.

Then again, something you may want to consider is just using Mix_Music* pointers with filenames, and SDL_mixer will do the streaming for you (doesn't necessarily have to be from fully-read memory RWops pointers).

**Comment by danellos** [comment]
I think I am simply not using it the way it was meant to be used. It might be that SDL is just not understanding the audio format being fed to it, and now its just assuming MOD or something. Browsing the source code of SDL_mixer seems to allude to that, but my understanding of it is not that intricate. 

Loading from files directly using filenames works fine, but it does not suit my problem because I am using a custom content loader, and SDL does not support using offsets for reading files (as far as I can tell, correct me if I am wrong). Creating and deleting temporary files before and after exit respectively is a possible solution, but to me that is perhaps too messy.

So I went for a slightly inefficient solution. It is inefficient because for a brief moment, there are two identical byte arrays in the managed and unmanaged part of memory, but it works.

````C#
byte[] mem = StreamHelper.ReadToEnd(_input);
var rwops = SDL.SDL_RWFromMem(mem, mem.Length);
PointerValue = SDL_mixer.Mix_LoadWAV_RW(rwops, 1);
ValidatePointer("Mix_LoadWAV_RW");
````

If this becomes a problem later, I will consider using a different library from SDL_mixer, as SDL_mixer is apparently "too low level" for many developers.

Thanks for your help!
