### ISSUE TITLE
Inconsistent Usage of Flag Enumerations

### ISSUE THREAD

**Issue by Super6-4** [flibitijibibo/SDL2-CS#91]
Just a small inconsistency.

SDL_CreateWindow() uses the SDL_WindowFlags enumeration for its flags parameter.
[Flag Usage in SDL_CreateWindow](../blob/master/src/SDL2.cs#L1075)

SDL_CreateRenderer() uses a uint parameter for its flags, rather than SDL_RendererFlags.
[Flag Usage in SDL_CreateRenderer](../blob/master/src/SDL2.cs#L1683)

**Comment by flibitijibibo** [comment]
https://github.com/flibitijibibo/SDL2-CS/commit/c41fcf5b19b8f778b41e6ded24313e3dfdf6a14e

We really should be using `uint` for the parameter types, but C#'s dumb and requires casts even when it knows the internal storage type, so here we are.
