### ISSUE TITLE
Using SDL2-CS

### ISSUE THREAD

**Issue by Lzard** [flibitijibibo/SDL2-CS#94]
Hello,

I discovered this SDL2 wrapper after playing around with Monogame and seeing it was used by Axiom Verge (and a few other games) for the Windows version (and probably the other desktop versions as well). As far as I know and have tested, FNA appears to be much more stable than Monogame, but since XNA is no longer being developped, I believe I shouldn't use it. Besides, I'd like to play around with OpenGL stuff myself (mostly because I would like to practice it and see how it works), and there are also a few parts of the XNA API that I do not like.

My plan is to write (sort of) an engine, using SDL2 and OpenGL (and probably OpenAL), and... Everything I'd need to do that in C# is here, thanks to you! So, here are a few questions about it:

- Regarding the use of C#, it is stated that SDL2-CS do not provide every SDL2 function. What functions exactly aren't provided? More generally, besides the portability relying on Mono and the performances, what are the cons of using C# over C/C++ with SDL2/OpenGL/OpenAL ?

- Would it be okay to copy (and change) the file OpenGLDevice_GL.cs from FNA (https://github.com/flibitijibibo/FNA/blob/master/src/Graphics/OpenGLDevice_GL.cs) to use OpenGL?

- Would MonoKickstart work with a project like this?

Thanks for the reply,
L zard

**Comment by flibitijibibo** [comment]
Axiom Verge only shipped with MonoGame on the PS4; FNA was used for all three desktop targets.

- There are two categories of things we don't have. The first is things that are available in C# without additional dependencies (for example, System.Threading has no dependencies, but System.Drawing does, so we try to support the SDL_Surface APIs). The second is any function we've not actually run into yet - we only try to cover stuff that we know for sure works, and that requires someone to use the function first. And, if you want my opinion, stay away from C# and just use C/C++ instead, possibly even staying away from most C++ features if you can. [Handmade Hero](https://handmadehero.org/) is a good learning resource that should tell you everything you need to know in this area.

- That'd be my recommended way of getting the GL entry points, so go for it.

- Yup.

**Comment by Lzard** [comment]
Hello,
Thanks for the opinion and the link, I will try and dig further into it!
I wanted to try this as I feel much more comfortable in C# than in C or C++, but I guess it would be better that I get more experience in those language.
Thanks for the quick reply!
L zard
