### ISSUE TITLE
Passing NULL to references

### ISSUE THREAD

**Issue by Yothri** [flibitijibibo/SDL2-CS#95]
Hi,

i would like to pass null to some functions for example RenderCopyEx to do default things.
It is not possible to do this right? Is there a good alternative?

**Comment by babelshift** [comment]
For what parameters? Pass IntPtr.Zero for the IntPtr parameters, null for the rects, and null for the center point. Angle and flip can't be null, so maybe that's what you meant?

**Comment by Yothri** [comment]
Hmm, i cant get it working: http://puu.sh/lFnlr/22865529c2.png

**Comment by babelshift** [comment]
Oh, right, the SDL_Rect and SDL_Point are structs. You cannot pass null for those.

**Comment by flibitijibibo** [comment]
Here's the prototype: https://github.com/flibitijibibo/SDL2-CS/blob/master/src/SDL2.cs#L1897

You probably want overloads like the ones for RenderCopy above that. Write them in and verify that they work on your end, then I'll merge them in.

**Comment by Yothri** [comment]
I am not yet familiar with GitHub, but i will try to create a Pull-Request and i will test if it works before i pull request :)

**Comment by flibitijibibo** [comment]
I believe this has been resolved with #96!
