### ISSUE TITLE
LPUtf8StrMarshaler.cs(83,29): error CS0019

### ISSUE THREAD

**Issue by 1vanK** [flibitijibibo/SDL2-CS#97]
```
- var mem = SDL.SDL_malloc((IntPtr) bytes.Length + 1);
+ var mem = SDL.SDL_malloc((IntPtr)(bytes.Length + 1));
```

**Comment by flibitijibibo** [comment]
Which compiler is complaining about this? The compilers we've verified with are the Mono 2.10 and 4.0 compilers in addition to Visual Studio 2010 and 2015.

**Comment by 1vanK** [comment]
```
set "PATH=c:\Windows\Microsoft.NET\Framework\v3.5\"
csc /unsafe /platform:x86 /target:library /out:SDL.dll *.cs
pause
```

**Comment by flibitijibibo** [comment]
Wait, is this with .NET 3.5...? Technically we don't support that, but if it works...

**Comment by flibitijibibo** [comment]
https://github.com/flibitijibibo/SDL2-CS/commit/a44c92397d77b7bcab74a86fae126f0f7ba7163e

**Comment by 1vanK** [comment]
> Wait, is this with .NET 3.5...? Technically we don't support that, but if it works...

There are no other problems at compile :)
